Add missing include
The missing include of ctype.h was found via the following warning by the
Debian buildd log scanner.

main.c: In function ‘_readBytesHex’:
main.c:347:9: warning: implicit declaration of function ‘toupper’ [-Wimplicit-function-declaration]
  347 |     c = toupper(c);
      |         ^~~~~~~